### ISSUE TITLE
BlackHoleLink: Create test for multiple input streams. 

### ISSUE THREAD

**Issue by CollinValley** [route-rs/route-rs#161]
Blackhole now supports multiple input streams, we should check that this work correctly.
Should:
1) Sink all packets from all streams
2) Roughly fairly trade-off between the streams. One stream shouldn't be starved because the other is always full. We won't achieve perfect fairness cause scheduling.

**Comment by eeverett6** [comment]
BlackHole doesn't support multiple input streams in the new Link API
