### ISSUE TITLE
Investigate combining common logic in Asynchronous links

### ISSUE THREAD

**Issue by CollinValley** [route-rs/route-rs#29]
We noticed that among AsyncElementLink, ClassifyElementLink, and JoinElementLink,  their subcomponents such as their consumers and producers, contain a lot of reoccurring logic.  We should try to compose this in a helper function.

**Comment by ddowl** [comment]
Leaving this issue open since there might be more possible refactoring among concurrent elements. This work might just fall under #32 though, in which case we can close this issue.
