### ISSUE TITLE
AsyncElementLink with queue_capacity zero deadlocks

### ISSUE THREAD

**Issue by eeverett6** [route-rs/route-rs#45]
Revisited my test case and realize the panic with a zero length queue doesn't actually occur until tear-down.  It is possible to create and start using an AsyncElementLink with queue capacity of 0, but it deadlocks. I also tested this on PR #42 and encountered the same issue.

**Comment by CollinValley** [comment]
Interesting, I have a commit in stack that changes the locking scheme, so this bug may go away, but in any case we should add an assert on length, since I don't think there is much expected behavior other than panic in this case.

**Comment by CollinValley** [comment]
@eeverett6  If you wish to add a small assert to satisfy your test case, and include that with your PR to close this bug, feel free. I'll work around any merge issues.
