### ISSUE TITLE
Rename "Consumer" and "Provider" to "UpstreamConsumer" and "DownstreamProvider" in concurrent elements

### ISSUE THREAD

**Issue by ddowl** [route-rs/route-rs#59]
We decided that the `Consumer` `Provider` names aren't clear enough in internal discussion. Let's update the `Consumer`s and `Provider`s of `AsyncElement`, `ClassifyElement`, and `JoinElement` with clearer names.

**Comment by rbrishabh** [comment]
I would like to take this up!

What names do I need to replace Consumer and Provider with?

**Comment by scgruber** [comment]
Hi @rbrishabh, thanks for reaching out. At this time, we're still very early and the project is changing quite a bit, so we're not taking contributions from developers who aren't already part of the team. Sorry for the confusion!

**Comment by rbrishabh** [comment]
haha! Didn't realize that! All the best with the project! =)

**Comment by ddowl** [comment]
Chatting with @CollinValley offline, @bweis will rename `Consumer` to `Ingressor` and `Provider` to `Egressor`. (these sound like pokemon).

**Comment by ddowl** [comment]
Closed by #78
