### ISSUE TITLE
Join element: Investigate use of Crossbeam selectors

### ISSUE THREAD

**Issue by moosingin3space** [route-rs/route-rs#61]
Crossbeam provides a [`Select`](https://docs.rs/crossbeam/0.7.2/crossbeam/channel/struct.Select.html) type that will choose among multiple input channels based on whichever one becomes ready first. This could possibly help with task waking in the `JoinElement`.

**Comment by CollinValley** [comment]
This selects randomly among the input streams for the next packet, and while that is fair ish and a bit faster, it is more fair to enforce that we round-robin for packets. Going to close this, perhaps we will create another join type called select that provides this functionality.
