### ISSUE TITLE
Discuss Pinning all our packages

### ISSUE THREAD

**Issue by CollinValley** [route-rs/route-rs#91]
We need to fully debate the best way to denote the versions of our dependencies in our cargo.toml files. Ideally we would set a specific version, maybe we could use more of a meta-version if they are available 'latest-stable' or whatever.

**Comment by moosingin3space** [comment]
If you use `cargo-edit` to add your dependencies, it automatically picks the latest version, and Cargo's default logic picks the most recent version that is semver-compatible.

**Comment by CollinValley** [comment]
That might be the best course of action.  Since then we get small updates, without any breaking changes
